version: '3.7'

services:
  imdtk:
    image: astrolabe/imdtk
    deploy:
      restart_policy:
        condition: none
    environment:
      PYTHONUNBUFFERED: 'true'
    volumes:
      - './images:/images:ro'


networks:
  default:
    external: true
    name: vos_net

volumes:
  pgdata:
