version: '3.9'

services:
  imdtk:
    image: astrolabe/imdtk
    restart: "no"
    environment:
      PYTHONUNBUFFERED: 'true'
    volumes:
      - './images:/images:ro'


networks:
  default:
    external: true
    name: vos_net

volumes:
  pgdata:
