# This file defines properties and default values for the ObsCore fields which
# are to be extracted, mapped, or computed from a FITS files.
#
#  Format: dictionary of dictionaries with format:
#          key => { required, default }
#   where:
#     key      = the ObsCore or custom keyword for the field to be extracted or created
#     required = true if field is required, false if optional
#     default  = optional default value for the field

#
# Mandatory ObsCore Data Model fields
#

# Observation Information (section B.1)
#
dataproduct_type = { required = true, default = "image" }
calib_level = { required = true, default = 3 }

# Target Information (section B.2)
#
target_name = { required = true }

# Data Descriptions (section B.3)
#
obs_id = { required = true, default = "FAKE_OBS_ID_1" }
obs_collection = { required = true, default = "JWST" }

# Curation Information (section B.4)
#
obs_publisher_did = { required = true, default = "ivo://astrolabe.arizona.edu/jwst" }

# Access Information (section B.5)
#
access_url = { required = true }
access_format = { required = true, default = "application/fits" }
access_estsize = { required = true }

# Spatial Characterisation (section B.6.1)
#
s_ra = { required = true }
s_dec = { required = true }
s_fov = { required = true }
s_region = { required = true }
s_resolution = { required = true }
s_xel1 = { required = true }
s_xel2 = { required = true }

# Spectral Characterisation (section B.6.2)
#
# em_xel = { required = true }
# em_min = { required = true }
# em_max = { required = true }
# em_res_power = { required = true }

# Time Characterisation (section B.6.3)
#
t_xel = { required = true }
t_min = { required = true }
t_max = { required = true }
t_exptime = { required = true }
t_resolution = { required = true }

# Observable Axis (section B.6.4)
#
o_ucd = { required = true, default = "phot.count" }

# Polarization Characterisation (section B.6.5)
#
# pol_xel = { required = true }
# pol_states = { required = true }

# Provenance (section B.7)
#
facility_name = { required = true, default = "JWST" }
instrument_name = { required = true }


#
# Non-Mandatory ObsCore Data Model fields
#
obs_creator_name = { required = false, default = "JWST" }


#
# DALserver Mandatory fields
#
spat_lolimit1 = { required = true }
spat_hilimit1 = { required = true }
spat_lolimit2 = { required = true }
spat_hilimit2 = { required = true }
im_scale = { required = true }
im_ra1 = { required = true }
im_dec1 = { required = true }
im_ra2 = { required = true }
im_dec2 = { required = true }
im_ra3 = { required = true }
im_dec3 = { required = true }
im_ra4 = { required = true }
im_dec4 = { required = true }
im_naxes = { required = true, default = 2 }
im_naxis1 = { required = true }
im_naxis2 = { required = true }
im_nsubarrays = { required = true, default = 1 }
im_pixtype = { required = true }
im_wcsaxes1 = { required = true }
im_wcsaxes2 = { required = true }

#
# DALserver needed
#
file_name = { required = true }
file_path = { required = true }

#
# JWST-specific fieldnames
#
is_public = { required = true, default = 0 }
equinox = { required = false, default = 2000.0 }
radesys = { required = false, default = "ICRS" }

nircam_channel = { required = false, default = "LONG" }
nircam_module = { required = false, default = "A" }
filter = { required = false }
pupil = { required = false, default = "CLEAR" }

# for JWST, DATE is the FITS timestamp (GMT):
gmt_date = { required = false }
