#!/bin/bash
#
# Shell script to run pipelines from inside the imdtk Docker file
# using the tools it contains. This script should be mounted by
# the container and runs within its environment.
#

# echo "ARGS=$*"

# echo "============================================"
# echo "All tools: show versions"
# echo "--------------------------------------------"
# cat_aliases -d --version
# csv_sink -d --version
# fields_info -d --version
# fits_cat_data -d --version
# fits_cat_fill -d --version
# fits_cat_md -d --version
# fits_cat_mktbl -d --version
# fits_cat_mktbl_pipe -d --version
# fits_cat_table_pipe -d --version
# fits_img_md -d --version
# img_aliases -d --version
# irods_fits_cat_md -d --version
# irods_fits_img_md -d --version
# irods_jwst_oc_calc -d --version
# irods_md_irods_pipe -d --version
# irods_md_pghyb_pipe -d --version
# irods_md_pgsql_pipe -d --version
# irods_mmd_irods_pipe -d --version
# irods_mmd_pghyb_pipe -d --version
# irods_mmd_pgsql_pipe -d --version
# jwst_oc_calc -d --version
# jwst_pghyb_sink -d --version
# jwst_pgsql_sink -d --version
# md_pghyb_pipe -d --version
# md_pgsql_pipe -d --version
# miss_report -d --version
# mmd_pghyb_pipe -d --version
# mmd_pgsql_pipe -d --version
# no_op -d --version
# pickle_sink -d --version

# echo "============================================"
# echo "All tools: show HELP"
# echo "--------------------------------------------"
# cat_aliases --help
# echo "--------------------------------------------"
# csv_sink --help
# echo "--------------------------------------------"
# fields_info --help
# echo "--------------------------------------------"
# fits_cat_data --help
# echo "--------------------------------------------"
# fits_cat_fill --help
# echo "--------------------------------------------"
# fits_cat_md --help
# echo "--------------------------------------------"
# fits_cat_mktbl --help
# echo "--------------------------------------------"
# fits_cat_mktbl_pipe --help
# echo "--------------------------------------------"
# fits_cat_table_pipe --help
# echo "--------------------------------------------"
# fits_img_md --help
# echo "--------------------------------------------"
# img_aliases --help
# echo "--------------------------------------------"
# irods_fits_cat_md --help
# echo "--------------------------------------------"
# irods_fits_img_md --help
# echo "--------------------------------------------"
# irods_jwst_oc_calc --help
# echo "--------------------------------------------"
# irods_md_irods_pipe --help
# echo "--------------------------------------------"
# irods_md_pghyb_pipe --help
# echo "--------------------------------------------"
# irods_md_pgsql_pipe --help
# echo "--------------------------------------------"
# irods_mmd_irods_pipe --help
# echo "--------------------------------------------"
# irods_mmd_pghyb_pipe --help
# echo "--------------------------------------------"
# irods_mmd_pgsql_pipe --help
# echo "--------------------------------------------"
# jwst_oc_calc --help
# echo "--------------------------------------------"
# jwst_pghyb_sink --help
# echo "--------------------------------------------"
# jwst_pgsql_sink --help
# echo "--------------------------------------------"
# md_pghyb_pipe --help
# echo "--------------------------------------------"
# md_pgsql_pipe --help
# echo "--------------------------------------------"
# miss_report --help
# echo "--------------------------------------------"
# mmd_pghyb_pipe --help
# echo "--------------------------------------------"
# mmd_pgsql_pipe --help
# echo "--------------------------------------------"
# no_op --help
# echo "--------------------------------------------"
# pickle_sink --help


# echo "============================================"
# echo "Headers only, verbose, to STANDARD OUTPUT:"
# echo "--------------------------------------------"
# fits_img_md -v -ff /vos/images/JADES/goods_s_F356W_2018_08_30.fits

# echo "============================================"
# echo "Headers only, named filename:"
# echo "--------------------------------------------"
# fits_img_md -v -ff /vos/images/JADES/goods_s_F356W_2018_08_30.fits -of /work/GOODS_F356W_headers.json

# echo "============================================"
# echo "Headers only, generated filename:"
# echo "--------------------------------------------"
# fits_img_md -v -ff /vos/images/JADES/goods_s_F356W_2018_08_30.fits -g

# echo "============================================"
# echo "Headers to img_aliases:"
# echo "--------------------------------------------"
# fits_img_md -v -ff /vos/images/DC19/F356W.fits | img_aliases -v -g

# echo "============================================"
# echo "Headers to img_aliases to fields_info:"
# echo "--------------------------------------------"
# fits_img_md -v -ff /vos/images/DC19/F356W.fits | img_aliases -v | fields_info -v -g

# echo "============================================"
# echo "Headers to img_aliases to fields_info to jwst_oc_calc:"
# echo "--------------------------------------------"
# fits_img_md -v -ff /vos/images/DC19/F356W.fits | img_aliases -v | fields_info -v | jwst_oc_calc -v -ff /vos/images/DC19/F356W.fits -g

# echo "============================================"
# echo "Headers to img_aliases to fields_info to jwst_oc_calc to miss_report:"
# echo "--------------------------------------------"
# fits_img_md -v -ff /vos/images/DC19/F356W.fits | img_aliases -v | fields_info -v | jwst_oc_calc -v -ff /vos/images/DC19/F356W.fits | miss_report -v -g

# echo "============================================"
# echo "Headers to img_aliases to fields_info to jwst_oc_calc to miss_report, specify COLLECTION:"
# echo "--------------------------------------------"
# fits_img_md -v -ff /vos/images/DC19/F356W.fits | img_aliases -v | fields_info -v | jwst_oc_calc -v -c TEST -ff /vos/images/DC19/F356W.fits | miss_report -v -g

# echo "============================================"
# echo "Headers to img_aliases to fields_info to jwst_oc_calc to miss_report to no_op:"
# echo "--------------------------------------------"
# fits_img_md -v -ff /vos/images/DC19/F356W.fits | img_aliases -v | fields_info -v | jwst_oc_calc -v -ff /vos/images/DC19/F356W.fits | miss_report -v | no_op -v -g

# echo "============================================"
# echo "Headers to img_aliases to fields_info to jwst_oc_calc to miss_report to no_op to pickle_sink:"
# echo "--------------------------------------------"
# fits_img_md -v -ff /vos/images/DC19/F356W.fits | img_aliases -v | fields_info -v | jwst_oc_calc -v -ff /vos/images/DC19/F356W.fits | miss_report -v | no_op -v | pickle_sink -v -g


# echo "============================================"
# echo "Pickle pipeline, generated filename:"
# echo "--------------------------------------------"
# fits_img_md -v -ff /vos/images/DC19/F356W.fits | img_aliases -v | fields_info -v | jwst_oc_calc -v -ff /vos/images/DC19/F356W.fits | miss_report -v | pickle_sink -v -g

# echo "============================================"
# echo "Pickle pipeline, named filename:"
# echo "--------------------------------------------"
# fits_img_md -v -ff /vos/images/DC19/F356W.fits | img_aliases -v | fields_info -v | jwst_oc_calc -v -ff /vos/images/DC19/F356W.fits | miss_report -v | pickle_sink -v -of /work/DC_F356W.pickle

# echo "============================================"
# echo "Pickle pipeline, all DEBUG:"
# echo "--------------------------------------------"
# fits_img_md -d -ff /vos/images/DC19/F356W.fits | img_aliases -d | fields_info -d | jwst_oc_calc -d -ff /vos/images/DC19/F356W.fits | miss_report -d | pickle_sink -d -g

# echo "============================================"
# echo "Pickle pipeline, all SILENT:"
# fits_img_md -ff /vos/images/DC19/F356W.fits | img_aliases | fields_info | jwst_oc_calc -ff /vos/images/DC19/F356W.fits | miss_report | pickle_sink -g


# echo "============================================"
# echo "PG SQL pipeline, generated filename:"
# echo "--------------------------------------------"
# fits_img_md -v -ff /vos/images/DC19/F356W.fits | img_aliases -v | fields_info -v | jwst_oc_calc -v -ff /vos/images/DC19/F356W.fits | miss_report -v | jwst_pgsql_sink -v -oo -g

# echo "============================================"
# echo "PG SQL pipeline, named filename:"
# echo "--------------------------------------------"
# fits_img_md -v -ff /vos/images/DC19/F356W.fits | img_aliases -v | fields_info -v | jwst_oc_calc -v -ff /vos/images/DC19/F356W.fits | miss_report -v | jwst_pgsql_sink -v -oo -of /work/testql.sql

# echo "============================================"
# echo "PG SQL pipeline, all DEBUG:"
# echo "--------------------------------------------"
# fits_img_md -d -ff /vos/images/DC19/F356W.fits | img_aliases -d | fields_info -d | jwst_oc_calc -d -ff /vos/images/DC19/F356W.fits | miss_report -d | jwst_pgsql_sink -d -oo -g

# echo "============================================"
# echo "PG SQL pipeline, all SILENT:"
# fits_img_md -ff /vos/images/DC19/F356W.fits | img_aliases | fields_info | jwst_oc_calc -ff /vos/images/DC19/F356W.fits | miss_report | jwst_pgsql_sink -oo -g


# echo "============================================"
# echo "CSV pipeline, generated filename:"
# echo "--------------------------------------------"
# fits_img_md -v -ff /vos/images/DC19/F356W.fits | img_aliases -v | fields_info -v | jwst_oc_calc -v -ff /vos/images/DC19/F356W.fits | miss_report -v | csv_sink -v -g

# echo "============================================"
# echo "CSV pipeline, named filename:"
# echo "--------------------------------------------"
# fits_img_md -v -ff /vos/images/DC19/F356W.fits | img_aliases -v | fields_info -v | jwst_oc_calc -v -ff /vos/images/DC19/F356W.fits | miss_report -v | csv_sink -v -of /work/test.csv

# echo "============================================"
# echo "csv pipeline, all debug:"
# echo "--------------------------------------------"
# fits_img_md -d -ff /vos/images/dc_191217/f356w.fits | img_aliases -d | fields_info -d | jwst_oc_calc -d -ff /vos/images/dc_191217/f356w.fits | miss_report -d | csv_sink -d -g

# echo "============================================"
# echo "CSV pipeline, all SILENT:"
# fits_img_md -ff /vos/images/DC19/F356W.fits | img_aliases | fields_info | jwst_oc_calc -ff /vos/images/DC19/F356W.fits | miss_report | csv_sink -g


# echo "============================================"
# echo "PG Hybrid pipeline, generated filename:"
# echo "--------------------------------------------"
# fits_img_md -v -ff /vos/images/DC19/F356W.fits | img_aliases -v | fields_info -v | jwst_oc_calc -v -ff /vos/images/DC19/F356W.fits | miss_report -v | jwst_pghyb_sink -v -oo -g

# echo "============================================"
# echo "PG Hybrid pipeline, named filename:"
# echo "--------------------------------------------"
# fits_img_md -v -ff /vos/images/DC19/F356W.fits | img_aliases -v | fields_info -v | jwst_oc_calc -v -ff /vos/images/DC19/F356W.fits | miss_report -v | jwst_pghyb_sink -v -oo -of /work/hyb1.sql

# echo "============================================"
# echo "PG Hybrid pipeline, all DEBUG:"
# echo "--------------------------------------------"
# fits_img_md -d -ff /vos/images/DC19/F356W.fits | img_aliases -d | fields_info -d | jwst_oc_calc -d -ff /vos/images/DC19/F356W.fits | miss_report -d | jwst_pghyb_sink -d -oo -g

# echo "============================================"
# echo "PG Hybrid pipeline, all SILENT:"
# fits_img_md -ff /vos/images/DC19/F356W.fits | img_aliases | fields_info | jwst_oc_calc -ff /vos/images/DC19/F356W.fits | miss_report | jwst_pghyb_sink -oo -g


# echo "============================================"
# echo "NO-OPs in various positions:"
# echo "--------------------------------------------"
# fits_img_md -v -ff /vos/images/DC19/F356W.fits | img_aliases -v | no_op -v -g
# fits_img_md -v -ff /vos/images/DC19/F356W.fits | no_op -v | img_aliases -v -g
# fits_img_md -d -ff /vos/images/DC19/F356W.fits | no_op -d | img_aliases -d -g


# echo "============================================"
# echo "Explicit intermediate file pipeline:"
# echo "--------------------------------------------"
# fits_img_md -d -ff /vos/images/DC19/F356W.fits -of /work/h.json
# img_aliases -d -if /work/h.json -of /work/ha.json
# fields_info -d -if /work/ha.json -of /work/hafi.json
# jwst_oc_calc -d -ff /vos/images/DC19/F356W.fits -if /work/hafi.json -of /work/hafijoc.json
# miss_report -d -if /work/hafijoc.json -of /work/hafijocmr.json
# pickle_sink -d -if /work/hafijocmr.json -of /work/hafijocmrpk.pickle
# jwst_pgsql_sink -d -oo -if /work/hafijocmr.json -of /work/hafijocmrsql.sql
# jwst_pghyb_sink -d -oo -if /work/hafijocmr.json -of /work/hafijocmrhyb.sql
# csv_sink -d -if /work/hafijocmr.json -of /work/hafijocmr.csv

# echo "============================================"
# echo "Explicit intermediate file pipeline with non-json names:"
# echo "--------------------------------------------"
# fits_img_md -d -ff /vos/images/DC19/F356W.fits -of /work/h1
# img_aliases -d -if /work/h1 -of /work/ha1
# fields_info -d -if /work/ha1 -of /work/hafi1
# jwst_oc_calc -d -ff /vos/images/DC19/F356W.fits -if /work/hafi1 -of /work/hafijoc1
# miss_report -d -if /work/hafijoc1 -of /work/hafijocmr1
# pickle_sink -d -if /work/hafijocmr1 -of /work/hafijocmrpk1
# jwst_pgsql_sink -d -oo -if /work/hafijocmr1 -of /work/hafijocmrsql1
# jwst_pghyb_sink -d -oo -if /work/hafijocmr1 -of /work/hafijocmrhyb1
# csv_sink -d -if /work/hafijocmr1 -of /work/hafijocmrcsv1


# echo "=================================================="
# echo "Exception catching on bad files (ERRORS EXPECTED):"
# echo "--------------------------------------------------"
# fits_img_md -ff /vos/images/BAD.fits -g -v
# fits_img_md -ff /vos/images/small_table.fits -g -v
# fits_img_md -ff /vos/images/NOSUCH.fits -g -v
# fits_img_md -ff /vos/images/m13.fits | pickle_sink -v
# fits_cat_md -ff /vos/images/BAD.fits -g -v
# fits_cat_md -ff /vos/images/m13.fits -g -v
# fits_cat_md -ff /vos/images/NOSUCH.fits -g -v


# echo "============================================"
# echo "Catalog Metadata:"
# echo "--------------------------------------------"
# fits_cat_md -ff /vos/catalogs/DC19/EAZY_results_summary_F356W.fits -d -g
# fits_cat_md -ff /vos/catalogs/DC19/EAZY_results_summary_F356W.fits -v -g
# fits_cat_md -ff /vos/catalogs/DC19/EAZY_results_summary_F356W.fits -v -of /work/ez_cat.json
# echo "--------------------------------------------"
# fits_cat_md -ff /vos/catalogs/DC19/Photometric_Catalog.F356W_kron_f80.fits -d -g
# fits_cat_md -v -ff /vos/catalogs/DC19/Photometric_Catalog.F356W_kron_f80.fits -v -g
# fits_cat_md -ff /vos/catalogs/DC19/Photometric_Catalog.F356W_kron_f80.fits -v -of /work/photo_cat.json


# echo "============================================"
# echo "Catalog Metadata with Aliases:"
# echo "--------------------------------------------"
# fits_cat_md -v -ff /vos/catalogs/small_table.fits | cat_aliases -v -g
# fits_cat_md -v -ff /vos/catalogs/small_table.fits | cat_aliases -v -of /work/small_table_fits_cat_md_alias.json


# echo "============================================"
# echo "Catalog Make Table:"
# echo "--------------------------------------------"
# fits_cat_md -v -ff /vos/catalogs/small_table.fits | fits_cat_mktbl -ct test_tbl -v -oo -g
# fits_cat_md -v -ff /vos/catalogs/small_table.fits | fits_cat_mktbl -ct test_tbl -v -oo -of /work/small_table_fits_cat_mktbl.sql
# echo "--------------------------------------------"
# fits_cat_md -v -ff /vos/catalogs/small_table.fits | cat_aliases -v | fits_cat_mktbl -ct test_tbl -v -oo -g
# fits_cat_md -v -ff /vos/catalogs/small_table.fits | cat_aliases -v | fits_cat_mktbl -ct test_tbl -v -oo -of /work/small_table_fits_cat_mktbl_alias.sql
# echo "--------------------------------------------"
# fits_cat_md -v -ff /vos/catalogs/small_table.fits | fits_cat_mktbl -ct noalias -v -oo -g
# fits_cat_md -v -ff /vos/catalogs/small_table.fits | fits_cat_mktbl -ct noalias -v -oo -of /work/small_table_fits_cat_mktbl_noalias.sql


# echo "============================================"
# echo "Catalog Data extraction:"
# echo "--------------------------------------------"
# Smallest (~60k) data file (with meta):
# fits_cat_data -v -ff /vos/catalogs/small_table.fits -v -g
# Medium sized (~1M) data file:
# fits_cat_data -v -ff /vos/catalogs/DC19/EAZY_results_summary_F356W.fits -v -g
# Medium sized (~2.9M) data file:
# fits_cat_data -v -ff /vos/catalogs/DC19/Photometric_Catalog.F200W_kron_f80.fits -v -g
# Largest (~4M) and most complex (nested fields) data file:
# fits_cat_data -v -ff /vos/catalogs/DC19/photometry_table_psf_matched_v5.0.fits -v -g


# echo "======================================================="
# echo "Single FITS metadata to PostgreSQL JWST table pipeline:"
# echo "-------------------------------------------------------"
# echo "BAD inputs or invalid arguments (ERRORS EXPECTED):"
# echo "--------------------------------------------------"
# md_pgsql_pipe -ff /vos/images/BAD.fits -g -v
# md_pgsql_pipe -ff /vos/images/small_table.fits -g -v
# md_pgsql_pipe -ff /vos/images/NOSUCH.fits -g -v
# echo "--------------------------------------------------"
# md_pgsql_pipe -ff /vos/images/DC19/F356W.fits -v -oo -g
# md_pgsql_pipe -ff /vos/images/DC19/F444W.fits -v -oo -g


# echo "==================================================================="
# echo "Single FITS metadata to PostgreSQL/JSON hybrid JWST table pipeline:"
# echo "-------------------------------------------------------------------"
# echo "BAD inputs or invalid arguments (ERRORS EXPECTED):"
# echo "--------------------------------------------------"
# md_pghyb_pipe -ff /vos/images/BAD.fits -g -v
# md_pghyb_pipe -ff /vos/images/small_table.fits -g -v
# md_pghyb_pipe -ff /vos/images/NOSUCH.fits -g -v
# echo "--------------------------------------------------"
# md_pghyb_pipe -ff /vos/images/DC19/F356W.fits -v -oo -g
# md_pghyb_pipe -ff /vos/images/DC19/F444W.fits -v -oo -g


# echo "========================================================="
# echo "Multiple FITS metadata to PostgreSQL JWST table pipeline:"
# echo "---------------------------------------------------------"
# mmd_pgsql_pipe -idir /tmp/nosuchdir -c JADES -oo -g -v
# echo "--------------------------------------------"
# mmd_pgsql_pipe -idir /vos/images/JADES -v
# mmd_pgsql_pipe -idir /vos/images/JADES -c JADES -v
# mmd_pgsql_pipe -idir /vos/images/JADES -oo -g -v
# echo "--------------------------------------------"
# mmd_pgsql_pipe -idir /vos/images/DC19 -v
# mmd_pgsql_pipe -idir /vos/images/DC19 -c DC19 -v
# mmd_pgsql_pipe -idir /vos/images/DC19 -oo -g -v
# echo "--------------------------------------------"
# mmd_pgsql_pipe -idir /vos/images -c TEST_ALL -v
# mmd_pgsql_pipe -idir /vos/images -c TEST_ALL -oo -g -v


# echo "====================================================================="
# echo "Multiple FITS metadata to hybrid PostgreSQL/JSON JWST table pipeline:"
# echo "---------------------------------------------------------------------"
# mmd_pghyb_pipe -idir /tmp/nosuchdir -c JADES -oo -g -v
# echo "--------------------------------------------"
# mmd_pghyb_pipe -idir /vos/images/JADES -v
# mmd_pghyb_pipe -idir /vos/images/JADES -c JADES -v
# mmd_pghyb_pipe -idir /vos/images/JADES -oo -g -v
# echo "--------------------------------------------"
# mmd_pghyb_pipe -idir /vos/images/DC19 -v
# mmd_pghyb_pipe -idir /vos/images/DC19 -c DC19 -v
# mmd_pghyb_pipe -idir /vos/images/DC19 -oo -g -v
# echo "--------------------------------------------"
# mmd_pghyb_pipe -idir /vos/images -c TEST_ALL -v
# mmd_pghyb_pipe -idir /vos/images -c TEST_ALL -oo -g -v


# echo "=================================================="
# echo "iRods Image Metadata extraction:"
# echo "--------------------------------------------------"
# echo "BAD inputs or invalid arguments (ERRORS EXPECTED):"
# echo "--------------------------------------------------"
# irods_fits_img_md -iff /iplant/home/hickst/vos/images/m14.fits -v
# irods_fits_img_md -iff /iplant/home/hickst/vos/images/BAD.fits -v
# irods_fits_img_md -iff /iplant/home/hickst/vos/images/m13.fits -v -hdu 1
# irods_fits_img_md -iff /iplant/home/hickst/vos/images/HorseHead.fits -v -hdu 1
# irods_fits_img_md -iff /iplant/home/hickst/vos/images/small_table.fits -v
# irods_fits_img_md -iff /iplant/home/hickst/vos/images/small_table.fits -v -hdu 1
# irods_fits_img_md -iff /iplant/home/hickst/astrolabe/data/w5/w5.fits -v -hdu 1
# irods_fits_img_md -iff /iplant/home/hickst/vos/images/DC19/F444W.fits -v -hdu 1
# irods_fits_img_md -iff /iplant/home/hickst/vos/catalogs/DC19/EAZY_results_summary_F356W.fits -v
# irods_fits_img_md -iff /iplant/home/hickst/vos/catalogs/DC19/EAZY_results_summary_F356W.fits -v -hdu 0
# irods_fits_img_md -iff /iplant/home/hickst/vos/catalogs/DC19/EAZY_results_summary_F356W.fits -v -hdu 1
# echo "--------------------------------------------------"
# irods_fits_img_md -iff /iplant/home/hickst/vos/images/m13.fits -g -v
# irods_fits_img_md -iff /iplant/home/hickst/vos/images/HorseHead.fits -g -v
# irods_fits_img_md -iff /iplant/home/hickst/astrolabe/data/w5/w5.fits -g -v
# irods_fits_img_md -iff /iplant/home/hickst/vos/images/DC19/F444W.fits -g -v


# echo "=================================================="
# echo "iRods Catalog Metadata extraction:"
# echo "--------------------------------------------------"
# echo "BAD inputs or invalid arguments (ERRORS EXPECTED):"
# echo "--------------------------------------------------"
# irods_fits_cat_md -iff /iplant/home/hickst/vos/images/m14.fits -v
# irods_fits_cat_md -iff /iplant/home/hickst/vos/images/BAD.fits -v
# irods_fits_cat_md -iff /iplant/home/hickst/vos/images/m13.fits -v
# irods_fits_cat_md -iff /iplant/home/hickst/vos/images/m13.fits -v -chdu 1
# irods_fits_cat_md -iff /iplant/home/hickst/vos/images/m13.fits -v -chdu 0
# irods_fits_cat_md -iff /iplant/home/hickst/vos/images/HorseHead.fits -v -chdu 0
# irods_fits_cat_md -iff /iplant/home/hickst/vos/images/small_table.fits -v -chdu 0
# irods_fits_cat_md -iff /iplant/home/hickst/astrolabe/data/w5/w5.fits -v
# irods_fits_cat_md -iff /iplant/home/hickst/astrolabe/data/w5/w5.fits -v -chdu 1
# irods_fits_cat_md -iff /iplant/home/hickst/astrolabe/data/w5/w5.fits -v -chdu 0
# irods_fits_cat_md -iff /iplant/home/hickst/vos/images/DC19/F444W.fits -v
# irods_fits_cat_md -iff /iplant/home/hickst/vos/images/DC19/F444W.fits -v -chdu 0
# irods_fits_cat_md -iff /iplant/home/hickst/vos/images/DC19/F444W.fits -v -chdu 1
# irods_fits_cat_md -iff /iplant/home/hickst/vos/catalogs/DC19/EAZY_results_summary_F356W.fits -v -chdu 0
# echo "--------------------------------------------------"
# irods_fits_cat_md -iff /iplant/home/hickst/vos/images/HorseHead.fits -g -v
# irods_fits_cat_md -iff /iplant/home/hickst/vos/images/HorseHead.fits -g -v -chdu 1
# irods_fits_cat_md -iff /iplant/home/hickst/vos/images/small_table.fits -g -v
# irods_fits_cat_md -iff /iplant/home/hickst/vos/images/small_table.fits -g -v -chdu 1
# irods_fits_cat_md -iff /iplant/home/hickst/vos/catalogs/DC19/EAZY_results_summary_F356W.fits -g -v
# irods_fits_cat_md -iff /iplant/home/hickst/vos/catalogs/DC19/EAZY_results_summary_F356W.fits -g -v -chdu 1


# echo "============================================================="
# echo "Single FITS iRods metadata to PostgreSQL JWST table pipeline:"
# echo "-------------------------------------------------------------"
# echo "BAD inputs or invalid arguments (ERRORS EXPECTED):"
# echo "--------------------------------------------------"
# irods_md_pgsql_pipe -iff /iplant/home/hickst/vos/images -v
# irods_md_pgsql_pipe -iff /iplant/home/hickst/vos/images/BAD.fits -v
# irods_md_pgsql_pipe -iff /iplant/home/hickst/vos/images/small_table.fits -v
# echo "-------------------------------------------------------------"
# irods_md_pgsql_pipe -iff /iplant/home/hickst/vos/images/m13.fits -oo -g -v
# irods_md_pgsql_pipe -iff /iplant/home/hickst/vos/images/HorseHead.fits -oo -g -v
# irods_md_pgsql_pipe -iff /iplant/home/hickst/vos/images/DC19/F444W.fits -oo -g -v
# irods_md_pgsql_pipe -iff /iplant/home/hickst/vos/images/DC19/F356W.fits -oo -g -v


# echo "========================================================================="
# echo "Single FITS iRods metadata to PostgreSQL/JSON hybrid JWST table pipeline:"
# echo "-------------------------------------------------------------------------"
# echo "BAD inputs or invalid arguments (ERRORS EXPECTED):"
# echo "--------------------------------------------------"
# irods_md_pghyb_pipe -iff /iplant/home/hickst/vos/images -v
# irods_md_pghyb_pipe -iff /iplant/home/hickst/vos/images/BAD.fits -v
# irods_md_pghyb_pipe -iff /iplant/home/hickst/vos/images/small_table.fits -v
# echo "-------------------------------------------------------------"
# irods_md_pghyb_pipe -iff /iplant/home/hickst/vos/images/m13.fits -oo -g -v
# irods_md_pghyb_pipe -iff /iplant/home/hickst/vos/images/HorseHead.fits -oo -g -v
# irods_md_pghyb_pipe -iff /iplant/home/hickst/vos/images/DC19/F444W.fits -oo -g -v
# irods_md_pghyb_pipe -iff /iplant/home/hickst/vos/images/DC19/F356W.fits -oo -g -v


# echo "==============================================================="
# echo "Multiple FITS iRods metadata to PostgreSQL JWST table pipeline:"
# echo "---------------------------------------------------------------"
# echo "BAD inputs or invalid arguments (ERRORS EXPECTED):"
# echo "--------------------------------------------------"
# irods_mmd_pgsql_pipe -idir /iplant/home/hickst/vos/nosuchdir -v
# echo "---------------------------------------------------------------"
# irods_mmd_pgsql_pipe -idir /iplant/home/hickst/resources -c EMPTY -v
# irods_mmd_pgsql_pipe -idir /iplant/home/hickst/vos/images/JADES -oo -g -v
# irods_mmd_pgsql_pipe -idir /iplant/home/hickst/vos/images/DC19 -oo -g -v


# echo "==========================================================================="
# echo "Multiple FITS iRods metadata to hybrid PostgreSQL/JSON JWST table pipeline:"
# echo "---------------------------------------------------------------------------"
# echo "BAD inputs or invalid arguments (ERRORS EXPECTED):"
# echo "--------------------------------------------------"
# irods_mmd_pghyb_pipe -idir /iplant/home/hickst/vos/nosuchdir -v
# echo "---------------------------------------------------------------------------"
# irods_mmd_pghyb_pipe -idir /iplant/home/hickst/resources -c EMPTY -v
# irods_mmd_pghyb_pipe -idir /iplant/home/hickst/vos/images/JADES -oo -g -v
# irods_mmd_pghyb_pipe -idir /iplant/home/hickst/vos/images/DC19 -oo -g -v


# echo "======================================================="
# echo "Single FITS iRods metadata back to iRods file pipeline:"
# echo "-------------------------------------------------------"
# echo "BAD inputs or invalid arguments (ERRORS EXPECTED):"
# echo "--------------------------------------------------"
# irods_md_irods_pipe -iff /iplant/home/hickst/nosuchdir -v
# irods_md_irods_pipe -iff /iplant/home/hickst/vos/images -v
# irods_md_irods_pipe -iff /iplant/home/hickst/vos/images/BAD.fits -v
# irods_md_irods_pipe -iff /iplant/home/hickst/vos/images/small_table.fits -v
# irods_md_irods_pipe -iff /iplant/home/hickst/vos/images/m13.fits -imd /iplant/tmp/nosuchfile -v
# echo "-------------------------------------------------------------"
# irods_md_irods_pipe -iff /iplant/home/hickst/vos/images/m13.fits -oo -g -v
# irods_md_irods_pipe -iff /iplant/home/hickst/vos/images/HorseHead.fits -oo -g -v
# irods_md_irods_pipe -iff /iplant/home/hickst/vos/images/DC19/F444W.fits -oo -g -v
# irods_md_irods_pipe -iff /iplant/home/hickst/vos/images/DC19/F356W.fits -oo -g -v
# echo "-------------------------------------------------------------"
# irods_md_irods_pipe -iff /iplant/home/hickst/vos/images/HorseHead.fits -imd /iplant/home/hickst/testDir/empty2.txt -v
# irods_md_irods_pipe -iff /iplant/home/hickst/vos/images/JADES/SubDir/m13_2.fits -v
# irods_md_irods_pipe -iff /iplant/home/hickst/vos/images/HorseHead.fits -v


# echo "=========================================================="
# echo "Multiple FITS iRods metadata back to iRods files pipeline:"
# echo "----------------------------------------------------------"
# echo "BAD inputs or invalid arguments (ERRORS EXPECTED):"
# echo "--------------------------------------------------"
# irods_mmd_irods_pipe -idir /iplant/home/hickst/vos/nosuchdir -v
# echo "---------------------------------------------------------------"
# irods_mmd_irods_pipe -idir /iplant/home/hickst/resources -c EMPTY -v
# irods_mmd_irods_pipe -idir /iplant/home/hickst/vos/images/JADES -oo -g -v
# irods_mmd_irods_pipe -idir /iplant/home/hickst/vos/images/DC19 -oo -g -v


# echo "============================================"
# echo "Current development:"
# echo "--------------------------------------------"
# echo ""
# echo "---------- Make table in DB: with aliases, w/o aliases, repetition failure  ----------"
# fits_cat_md -ff /vos/catalogs/small_table.fits | fits_cat_mktbl -ct test_tbl -v
# fits_cat_md -ff /vos/catalogs/small_table.fits | cat_aliases -v | fits_cat_mktbl -ct test_tbl2 -v
# fits_cat_md -ff /vos/catalogs/small_table.fits | fits_cat_mktbl -ct test_tbl -v


# echo "---------- Make table Pipeline ----------"
# fits_cat_mktbl_pipe -ff /vos/catalogs/small_table.fits -ct test_tbl -oo -g -v
# fits_cat_mktbl_pipe -ff /vos/catalogs/small_table.fits -ct test_tbl -v

# fits_cat_md -ff /vos/catalogs/small_table.fits | fits_cat_mktbl -ct test_tbl -v
# fits_cat_data -ff /vos/catalogs/small_table.fits -v | fits_cat_fill -ct test_tbl -v -oo -g
# fits_cat_data -ff /vos/catalogs/small_table.fits -v | fits_cat_fill -ct test_tbl -v


# echo "---------- Fill table Pipeline ----------"
# fits_cat_table_pipe -ff /vos/catalogs/small_table.fits -ct test_tbl -v -oo -g


# echo "---------- Make & Fill table Pipeline ----------"
# fits_cat_md -ff /vos/catalogs/small_table.fits | cat_aliases -v | fits_cat_mktbl -ct test_tbl2 -v
# fits_cat_mktbl_pipe -ff /vos/catalogs/small_table.fits -ct test_tbl2 -v
# fits_cat_mktbl_pipe -ff /vos/catalogs/small_table.fits -a /imdtk/config/jwst-cat-aliases.ini -ct test_tbl2 -v
# fits_cat_table_pipe -ff /vos/catalogs/small_table.fits -ct test_tbl2 -v

# Medium sized (~1M) data file:
# fits_cat_mktbl_pipe -ff /vos/catalogs/DC19/EAZY_results_summary_F356W.fits -a /imdtk/config/jwst-cat-aliases.ini -ct test_ez -v
# fits_cat_mktbl_pipe -ff /vos/catalogs/DC19/EAZY_results_summary_F356W.fits -ct test_ez -v
# fits_cat_table_pipe -ff /vos/catalogs/DC19/EAZY_results_summary_F356W.fits -ct test_ez -v

# Medium sized (~2.9M) data file:
# fits_cat_mktbl_pipe -ff /vos/catalogs/DC19/Photometric_Catalog.F200W_kron_f80.fits -a /imdtk/config/jwst-cat-aliases.ini -ct test_pho -v
# fits_cat_mktbl_pipe -ff /vos/catalogs/DC19/Photometric_Catalog.F200W_kron_f80.fits -ct test_pho -v
# fits_cat_table_pipe -ff /vos/catalogs/DC19/Photometric_Catalog.F200W_kron_f80.fits -ct test_pho -v


# echo "---------- Extract JWST ObsCore info from iRods FITS file ----------"
# irods_fits_img_md -iff /iplant/home/hickst/vos/images/DC19/F444W.fits -v | img_aliases -v | fields_info -v | irods_jwst_oc_calc -iff /iplant/home/hickst/vos/images/DC19/F444W.fits -v -g


# echo "---------- Store iRods image MD to SQL & Hybrid tables ----------"
# irods_fits_img_md -iff /iplant/home/hickst/vos/images/DC19/F444W.fits -v | img_aliases -v | fields_info -v | irods_jwst_oc_calc -iff /iplant/home/hickst/vos/images/DC19/F444W.fits -v -g

# irods_fits_img_md -iff /iplant/home/hickst/vos/images/DC19/F444W.fits -v | img_aliases -v | fields_info -v | irods_jwst_oc_calc -iff /iplant/home/hickst/vos/images/DC19/F444W.fits -v | miss_report | jwst_pgsql_sink -v

# irods_fits_img_md -iff /iplant/home/hickst/vos/images/DC19/F444W.fits -v | img_aliases -v | fields_info -v | irods_jwst_oc_calc -iff /iplant/home/hickst/vos/images/DC19/F444W.fits -v | miss_report | jwst_pghyb_sink -v

# irods_fits_img_md -iff /iplant/home/hickst/vos/images/DC19/F356W.fits -v | img_aliases -v | fields_info -v | irods_jwst_oc_calc -iff /iplant/home/hickst/vos/images/DC19/F356W.fits -v | miss_report | jwst_pgsql_sink -v

# irods_fits_img_md -v -iff /iplant/home/hickst/vos/images/DC19/F356W.fits | img_aliases | fields_info | irods_jwst_oc_calc -iff /iplant/home/hickst/vos/images/DC19/F356W.fits | miss_report | jwst_pghyb_sink -v

# mmd_pghyb_pipe -idir /vos/images/JADES -c JADES -v
# mmd_pghyb_pipe -idir /vos/images/DC19 -c DC19 -v

# echo "============================================"
