#!/bin/bash
#
# Shell script to run pipelines from inside the imdtk Docker file
# using the tools it contains. This script should be mounted by
# the container and runs within its environment.
#

# echo "ARGS=$*"

# echo "============================================"
# echo " Catalog extraction, creation, and loading  "
# echo "--------------------------------------------"
# fits_cat_md -ff /vos/catalogs/DC20/hd_all.cat.fits -g -v
# fits_cat_md -v -ff /vos/catalogs/DC20/hd.cat.fits | cat_aliases -v -g
# fits_cat_md -v -ff /vos/catalogs/DC20/hd_all.cat.fits | cat_aliases -v -g
# fits_cat_md -v -ff /vos/catalogs/DC20/hd_all.cat.fits | cat_aliases -v | fits_cat_mktbl -ct test_tbl -v -oo -g

fits_cat_mktbl_pipe -v -ff /vos/catalogs/DC20/hd_all.cat.fits -ct hd_all_dc20
fits_cat_table_pipe -v -ff /vos/catalogs/DC20/hd_all.cat.fits -ct hd_all_dc20


# echo "============================================"
# echo " Pipelines to restore image metadata DB     "
# echo "--------------------------------------------"
# echo " For jtest testing table:"
# echo "--------------------------------------------"
# mmd_pgsql_pipe -tn jtest -idir /vos/images/JADES -c JADES -v
# mmd_pgsql_pipe -tn jtest -idir /vos/images/DC19 -c DC19 -v
# mmd_pgsql_pipe -tn jtest -idir /vos/images/DC20 -c DC20 -v
# mmd_pgsql_pipe -tn jtest -idir /vos/images/XTRAS -c XTRAS -v
# mmd_pgsql_pipe -tn jtest -idir /vos/images/XTRAS -c TEST -v

# echo "--------------------------------------------"
# echo " For jwst image table:"
# echo "--------------------------------------------"
# mmd_pgsql_pipe -idir /vos/images/JADES -c JADES -v
# mmd_pgsql_pipe -idir /vos/images/DC19 -c DC19 -v
# mmd_pgsql_pipe -idir /vos/images/DC20 -c DC20 -v
# mmd_pgsql_pipe -idir /vos/images/XTRAS -c XTRAS -v

# md_pgsql_pipe -tn jtest -ff /vos/images/XTRAS/HorseHead.fits -c XTRAS -v -d
# md_pgsql_pipe -tn jtest -ff tests/resources/HorseHead.fits -c TEST -v
# md_pgsql_pipe -tn jtest -ff tests/resources/m13.fits -c TEST -v


# fits_img_md -d -ff /vos/images/XTRAS/HorseHead.fits
# fits_img_md -d -ff /vos/images/XTRAS/HorseHead.fits | img_aliases -d | fields_info -d | jwst_oc_calc -d -ff /vos/images/DC19/F356W.fits | miss_report -d | jwst_pgsql_sink -tn jtest -c XTRAS -d

# mmd_pghyb_pipe -idir /vos/images/JADES -c JADES -v
# mmd_pghyb_pipe -idir /vos/images/DC19 -c DC19 -v
# mmd_pghyb_pipe -idir /vos/images/DC20 -c DC20 -v

# fits_img_md -v -ff /vos/images/DC19/F356W.fits | img_aliases -v | fields_info -v | jwst_oc_calc -v -ff /vos/images/DC19/F356W.fits -g
# fits_img_md -v -ff /vos/images/DC20/F090W.fits | img_aliases -v | fields_info -v | jwst_oc_calc -v -ff /vos/images/DC20/F090W.fits -g


# echo "=========================================================="
# echo "Sink input metadata to iRods file:"
# echo "--------------------------------------------------"
# echo "BAD inputs or invalid arguments (ERRORS EXPECTED):"
# echo "--------------------------------------------------"
# irods_md_sink -if ./tests/resources/test-md.json -imd /iplant/tmp/nosuchfile -v
# echo "--------------------------------------------------"
# irods_md_sink -if ./tests/resources/test-md-empty.json -imd /iplant/home/hickst/testDir/empty2.txt -v
# irods_md_sink -if ./tests/resources/test-md.json -imd /iplant/home/hickst/testDir/empty2.txt -v
# irods_md_sink -if ./tests/resources/test-md.json -imd /iplant/home/hickst/testDir/empty2.txt -rm -v
# irods_md_sink -if ./tests/resources/test-md-full.json -imd /iplant/home/hickst/testDir/empty3.txt -v
# irods_md_sink -if ./tests/resources/test-md-full.json -imd /iplant/home/hickst/testDir/empty3.txt --remove -v

# fits_img_md -v -ff /vos/images/XTRAS/HorseHead.fits | img_aliases -v | fields_info -v | jwst_oc_calc -v -ff /vos/images/XTRAS/HorseHead.fits -g

# echo "============================================"
